twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - form/theme.html.twig
    globals:
        enabled_locales: '%enabled_locales%'

when@test:
    twig:
        strict_variables: true
